spring:
  mail:
    properties:
      mail:
        smtp:
          socketFactory:
            port: '465'
            class: javax.net.ssl.SSLSocketFactory
            fallback: 'false'
          auth: 'true'
    host: smtp.gmail.com
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    password: ${PASSWORD}
    username: ${USERNAME}
    url: ${URL}
twitter:
  token:
    nodeValue: ${TWITTER_TOKEN}
    secret: ${TWITTER_TOKEN_SECRET}
  api:
    url: https://api.twitter.com/2/
  bearer: ${TWITTER_BEARER}
  consumer:
    secret: ${TWITTER_CONSUMER_SECRET}
    key: ${TWITTER_CONSUMER_KEY}
server:
  port: '4001'
